/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*! @name PORTA2 (number 36), J9[6]/TRACE_SWO
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_TRACE_SWO_PORT PORTA               /*!<@brief PORT peripheral base pointer */
#define BOARD_TRACE_SWO_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_TRACE_SWO_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                 /* @} */

/*! @name PORTC16 (number 90), J1[7]/LPUART0_RX
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_LPUART0_RX_PORT PORTC                /*!<@brief PORT peripheral base pointer */
#define BOARD_LPUART0_RX_PIN 16U                   /*!<@brief PORT pin number */
#define BOARD_LPUART0_RX_PIN_MASK (1U << 16U)      /*!<@brief PORT pin mask */
                                                   /* @} */

/*! @name PORTC17 (number 91), J1[9]/LPUART0_TX
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_LPUART0_TX_PORT PORTC                /*!<@brief PORT peripheral base pointer */
#define BOARD_LPUART0_TX_PIN 17U                   /*!<@brief PORT pin number */
#define BOARD_LPUART0_TX_PIN_MASK (1U << 17U)      /*!<@brief PORT pin mask */
                                                   /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

/*! @name PORTE4 (number 5), SW3
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_SW3_GPIO GPIOE               /*!<@brief GPIO peripheral base pointer */
#define BOARD_SW3_GPIO_PIN_MASK (1U << 4U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_SW3_PORT PORTE               /*!<@brief PORT peripheral base pointer */
#define BOARD_SW3_PIN 4U                   /*!<@brief PORT pin number */
#define BOARD_SW3_PIN_MASK (1U << 4U)      /*!<@brief PORT pin mask */
                                           /* @} */

/*! @name PORTA4 (number 38), SW2/NMI_b
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_SW2_GPIO GPIOA               /*!<@brief GPIO peripheral base pointer */
#define BOARD_SW2_GPIO_PIN_MASK (1U << 4U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_SW2_PORT PORTA               /*!<@brief PORT peripheral base pointer */
#define BOARD_SW2_PIN 4U                   /*!<@brief PORT pin number */
#define BOARD_SW2_PIN_MASK (1U << 4U)      /*!<@brief PORT pin mask */
                                           /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitBUTTONsPins(void);

#define PORT_DFER_DFE_1_MASK 0x02u /*!<@brief Digital Filter Enable Mask for item 1. */
#define PORT_DFER_DFE_7_MASK 0x80u /*!<@brief Digital Filter Enable Mask for item 7. */

/*! @name PORTE25 (number 32), D4[3]/LEDRGB_BLUE
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_LED_BLUE_GPIO GPIOE                /*!<@brief GPIO peripheral base pointer */
#define BOARD_LED_BLUE_GPIO_PIN_MASK (1U << 25U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_LED_BLUE_PORT PORTE                /*!<@brief PORT peripheral base pointer */
#define BOARD_LED_BLUE_PIN 25U                   /*!<@brief PORT pin number */
#define BOARD_LED_BLUE_PIN_MASK (1U << 25U)      /*!<@brief PORT pin mask */
                                                 /* @} */

/*! @name PORTD1 (number 94), D4[1]/LEDRGB_RED
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_LED_RED_GPIO GPIOD               /*!<@brief GPIO peripheral base pointer */
#define BOARD_LED_RED_GPIO_PIN_MASK (1U << 1U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_LED_RED_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_LED_RED_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_LED_RED_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                               /* @} */

/*! @name PORTD7 (number 100), D4[4]/LEDRGB_GREEN
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_LED_GREEN_GPIO GPIOD               /*!<@brief GPIO peripheral base pointer */
#define BOARD_LED_GREEN_GPIO_PIN_MASK (1U << 7U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_LED_GREEN_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_LED_GREEN_PIN 7U                   /*!<@brief PORT pin number */
#define BOARD_LED_GREEN_PIN_MASK (1U << 7U)      /*!<@brief PORT pin mask */
                                                 /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitLEDsPins(void);

#define SOPT5_UART0TXSRC_UART_TX 0x00u /*!<@brief UART 0 transmit data source select: UART0_TX pin */

/*! @name PORTB16 (number 62), U7[4]/UART0_RX_TGTMCU
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_DEBUG_UART_RX_PORT PORTB                /*!<@brief PORT peripheral base pointer */
#define BOARD_DEBUG_UART_RX_PIN 16U                   /*!<@brief PORT pin number */
#define BOARD_DEBUG_UART_RX_PIN_MASK (1U << 16U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*! @name PORTB17 (number 63), U10[1]/UART0_TX_TGTMCU
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_DEBUG_UART_TX_PORT PORTB                /*!<@brief PORT peripheral base pointer */
#define BOARD_DEBUG_UART_TX_PIN 17U                   /*!<@brief PORT pin number */
#define BOARD_DEBUG_UART_TX_PIN_MASK (1U << 17U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitDEBUG_UARTPins(void);

/*! @name ADC1_DP1 (number 16), RT1/THER_A
  @{ */
/* @} */

/*! @name ADC1_DM1 (number 17), RT1/THER_B
  @{ */
/* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitTHERPins(void);

/*! @name PORTA18 (number 50), X501[1]/EXTAL0
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_EXTAL0_PORT PORTA                /*!<@brief PORT peripheral base pointer */
#define BOARD_EXTAL0_PIN 18U                   /*!<@brief PORT pin number */
#define BOARD_EXTAL0_PIN_MASK (1U << 18U)      /*!<@brief PORT pin mask */
                                               /* @} */

/*! @name PORTA19 (number 51), X501[3]/XTAL0
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_XTAL0_PORT PORTA                /*!<@brief PORT peripheral base pointer */
#define BOARD_XTAL0_PIN 19U                   /*!<@brief PORT pin number */
#define BOARD_XTAL0_PIN_MASK (1U << 19U)      /*!<@brief PORT pin mask */
                                              /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitOSCPins(void);

/*! @name PORTD2 (number 95), U8[4]/I2C0_SCL
  @{ */

/* Symbols to be used with PORT driver */
#define I2C0_INITPINS_ACCEL_SCL_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define I2C0_INITPINS_ACCEL_SCL_PIN 2U                   /*!<@brief PORT pin number */
#define I2C0_INITPINS_ACCEL_SCL_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORTD3 (number 96), U8[6]/I2C0_SDA
  @{ */

/* Symbols to be used with PORT driver */
#define I2C0_INITPINS_ACCEL_SDA_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define I2C0_INITPINS_ACCEL_SDA_PIN 3U                   /*!<@brief PORT pin number */
#define I2C0_INITPINS_ACCEL_SDA_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void I2C0_InitPins(void);

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void I2C0_DeinitPins(void);

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void I2C1_InitPins(void);

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void I2C1_DeinitPins(void);

#define SOPT5_UART1TXSRC_UART_TX 0x00u /*!<@brief UART 1 transmit data source select: UART1_TX pin */

/*! @name PORTC9 (number 81), J4[4]/ADC1_SE5b/CMP0_IN3
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITBLUETOOTH_BT_MONITOR_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITBLUETOOTH_BT_MONITOR_GPIO_PIN_MASK (1U << 9U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITBLUETOOTH_BT_MONITOR_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITBLUETOOTH_BT_MONITOR_PIN 9U                   /*!<@brief PORT pin number */
#define BOARD_INITBLUETOOTH_BT_MONITOR_PIN_MASK (1U << 9U)      /*!<@brief PORT pin mask */
                                                                /* @} */

/*! @name PORTC8 (number 80), J4[2]/ADC1_SE4b/CMP0_IN2
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITBLUETOOTH_BT_WACKUP_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITBLUETOOTH_BT_WACKUP_GPIO_PIN_MASK (1U << 8U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITBLUETOOTH_BT_WACKUP_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITBLUETOOTH_BT_WACKUP_PIN 8U                   /*!<@brief PORT pin number */
#define BOARD_INITBLUETOOTH_BT_WACKUP_PIN_MASK (1U << 8U)      /*!<@brief PORT pin mask */
                                                               /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitBluetooth(void);

#define SOPT4_FTM2CH0SRC_FTM 0x00u /*!<@brief FTM2 channel 0 input capture source select: FTM2_CH0 signal */
#define SOPT4_FTM2CH1SRC_FTM 0x00u /*!<@brief FTM2 channel 1 input capture source select: FTM2_CH1 signal */

/*! @name PORTC1 (number 71), J3[15]/FTM0_CH0
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITMOTORDRIVERSHIELD_PWM_AT_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITMOTORDRIVERSHIELD_PWM_AT_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITMOTORDRIVERSHIELD_PWM_AT_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                                    /* @} */

/*! @name PORTC2 (number 72), J3[13]/FTM0_CH1
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITMOTORDRIVERSHIELD_PWM_AB_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITMOTORDRIVERSHIELD_PWM_AB_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_INITMOTORDRIVERSHIELD_PWM_AB_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                                    /* @} */

/*! @name PORTC5 (number 77), J3[11]/FTM0_CH2
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITMOTORDRIVERSHIELD_PWM_BT_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITMOTORDRIVERSHIELD_PWM_BT_PIN 5U                   /*!<@brief PORT pin number */
#define BOARD_INITMOTORDRIVERSHIELD_PWM_BT_PIN_MASK (1U << 5U)      /*!<@brief PORT pin mask */
                                                                    /* @} */

/*! @name PORTC4 (number 76), J3[9]/FTM0_CH3
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITMOTORDRIVERSHIELD_PWM_BB_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITMOTORDRIVERSHIELD_PWM_BB_PIN 4U                   /*!<@brief PORT pin number */
#define BOARD_INITMOTORDRIVERSHIELD_PWM_BB_PIN_MASK (1U << 4U)      /*!<@brief PORT pin mask */
                                                                    /* @} */

/*! @name PORTD4 (number 97), J3[7]/FTM0_CH4
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITMOTORDRIVERSHIELD_PWM_CT_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITMOTORDRIVERSHIELD_PWM_CT_PIN 4U                   /*!<@brief PORT pin number */
#define BOARD_INITMOTORDRIVERSHIELD_PWM_CT_PIN_MASK (1U << 4U)      /*!<@brief PORT pin mask */
                                                                    /* @} */

/*! @name PORTD5 (number 98), J3[5]/FTM0_CH5
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITMOTORDRIVERSHIELD_PWM_CB_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITMOTORDRIVERSHIELD_PWM_CB_PIN 5U                   /*!<@brief PORT pin number */
#define BOARD_INITMOTORDRIVERSHIELD_PWM_CB_PIN_MASK (1U << 5U)      /*!<@brief PORT pin mask */
                                                                    /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitMotorDriverShield(void);

/*! @name PORTC0 (number 70), J4[8]/ADC0_SE14
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITSPI0_ADC0_SE14_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITSPI0_ADC0_SE14_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_INITSPI0_ADC0_SE14_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitSPI0(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
